Index.js Error when trying to include jQuery.
/Users/pam/git/yap/routes/index.js:21
$(document).ready(function() {
^
ReferenceError: $ is not defined
    at Object.<anonymous> (/Users/pam/git/yap/routes/index.js:21:1)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/pam/git/yap/app.js:11:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)